### ISSUE TITLE
users.views.charge_wallet()の修正

### ISSUE THREAD

**Issue by sanoto** [tnct-spc/kagipos#12]
transactionを追加すれば自動的にuser.walletにも反映されるようにした(apiブランチの 88e352c)のでtransactionを追加するだけにする

**Comment by fazerog02** [comment]
apiブランチをマージして作業したほうが良さそうですが，マージして大丈夫ですか？

**Comment by sanoto** [comment]
やっても大丈夫だと思うよ

**Comment by fazerog02** [comment]
6d2ac27 でmergeしました

**Comment by fazerog02** [comment]
7f8718c で対応しました．

ところで，possys/views.add_transactionのことなんですが，
users/views.charge_walletでadd_transactionにidmを渡すときに，charge_wallet側でidmを手に入れるにはcardを経由する必要があって，そのせいでadd_transaction内のidmチェックが無駄になっているので
add_transactionの引数をidmからuserにしたほうが良いと思うのですが，どうですか？

**Comment by sanoto** [comment]
確かにそのほうがいいな・・・

**Comment by sanoto** [comment]
[上の指摘](https://github.com/tnct-spc/kagipos/issues/12#issuecomment-487507761)には
#20 のissueを立てて #21 で対応した
