### ISSUE TITLE
formのviewをできるだけ簡素化

### ISSUE THREAD

**Issue by sanoto** [tnct-spc/kagipos#13]
LoginViewなど、class based viewに置き換える
モデルベースなビューはクラス使って簡素化しましょうねという話

**Comment by fazerog02** [comment]
1f693aa で対応しました．

**Comment by sanoto** [comment]
@fazerog02 
SignupViewはもっと簡潔に書けるので[ここ](https://qiita.com/NAKKA-K/items/d96a683ea59409abc340)を参考に実装すべし
フォームは今のままで大丈夫
ログイン処理も一緒にやっちゃいたければform_validメソッドがあるので、そこにCardCreateViewみたいな感じで処理を付け足す

**Comment by fazerog02** [comment]
7896a02 で対応しました．
