### ISSUE TITLE
add_cardページ実装

### ISSUE THREAD

**Issue by sanoto** [tnct-spc/kagipos#14]
usersアプリにadd_cardページを実装する
ロジック部は書いたので、以下をコピペしたうえでCardCreateViewのテンプレートを実装するべし

users/urls.py
```python
path('add_card/<uuid>/', users_views.CardCreateView.as_view()),
```
users/views.py
```python
from django.views.generic.edit import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Temporary, Card


class CardCreateView(LoginRequiredMixin, CreateView):
    model = Card
    fields = ['name']

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.idm = Temporary.objects.get(uuid=self.kwargs['uuid'])
        return super().form_valid(form)
```

**Comment by fazerog02** [comment]
486b679 で対応しました．

ただ，テストしたところTemporaryのuuidを16桁にしているのに
uuidが20桁なのでダメというエラーがでたので，users/viewsの47行目の
`Temporary.objects.get(uuid=self.kwargs['uuid'])`
のあとに`.idm`をつけてみたら通るようになったのでつけ忘れだと思うのですが，どうですか？
あと，上記の点を直したあとに
`No URL to redirect to.  Either provide a url or define a get_absolute_url method on the Model.`
というエラーがでるようになったのでそこも報告しておきます．

**Comment by sanoto** [comment]
あ
完全につけ忘れですね、はい。

**Comment by sanoto** [comment]
URLの方は・・・
success_urlかな？
なんか作り終わったあとに飛ばしたいURL入れとけばいいと思う
まあ取り敢えずpossys/に飛ばすのが無難かね

**Comment by fazerog02** [comment]
02498f6 で直しておきました．
