### ISSUE TITLE
リファクタリング

### ISSUE THREAD

**Issue by sanoto** [tnct-spc/kagipos#2]
# 概要
コードの書き方が意外とアレなので早めに直しておきましょう
## PyCharmを活用しよう
コード中と右端のスクロールバーにいろいろ出ているので、それに従って直す
黄色の波線が警告、緑色の波線はスペルミス(possysなどの造語の場合は気にしなくて良い)
## Git連携
git addする前に、git statusでcommitするべきものを選別するのはもちろんのことだが、その前に、IDEのディレクトリ表示エリアを見て、余計な変更をしていないか見たほうがよい
変更したファイル名の色が変わっているはずなのでそれを見る
また、IDEのGit連携の設定もやっておくと良い
CUIで抜けが出るのが心配ならIDEのGUIで全てのGit操作を行う
GUIでdiff等をわかりやすく表示してくれるので間違いが起こりにくくなる
## クラスや関数の場所
新しく作るクラスや関数やちゃんとアプリごとに分別して配置しましょう
モデルを基準に考えると良い
例えばUserやCardやTemporaryに関する処理はusersアプリの中に書くべき
## app/migrations/*
今回は消さない方針で行く

**Comment by fazerog02** [comment]
fd4bbcaで対応しました．

## 主な変更点
・typoを直した．
・関数名で大文字を使わないようにした．  ex(ChargeWallet -> charge_wallet)
　＋それに伴ったファイル名の変更
・signup, login, logout, charge_wallet関係のコードをpossysからusersに移した．

**Comment by fazerog02** [comment]
すみません．users/urls.pyのaddがうまくできていなかったので 6d6c23e でaddしました．

**Comment by fazerog02** [comment]
settings.pyあたりでやり残しがあったので d70c64a で対応しました．

**Comment by sanoto** [comment]
@fazerog02 masterをマージして、kagipos/urlsにusers/urlsを追加して

**Comment by fazerog02** [comment]
2a528b8 margeして 739e036 で対応しました．

**Comment by sanoto** [comment]
masterにマージしてmigrateやり直したのをmasterにコミットした
