### ISSUE TITLE
Transaction.save()の修正案

### ISSUE THREAD

**Issue by fazerog02** [tnct-spc/kagipos#24]
ProductモデルのpriceがPositiveIntegerになっていてAPIではurlの引数に負の値を使えないため，今のTransactionモデルのsaveの
`self.user.wallet += self.price`
のままだと商品の購入処理が行えないので，
ProductモデルのpriceをIntegerにして負で設定するか
今のTransactionモデルのsaveの`self.user.wallet += self.price`を
`self.user.wallet -= self.price`
に変更して，通常の購入は正の値で入金は負の値でするべきだと思うのですが，どうですか？

**Comment by sanoto** [comment]
#21 でもうやってある
分かりにくいけど、add_transactionのpriceにproduct.priceのマイナスを渡してる

**Comment by sanoto** [comment]
@fazerog02 把握したら閉じといて

**Comment by fazerog02** [comment]
了解です
