### ISSUE TITLE
確認ダイアログの部分を切り出して一般化し、ログアウト等でも使い回せるようにする

### ISSUE THREAD

**Issue by sanoto** [tnct-spc/kagipos#25]
テンプレートとして切り出し、[これみたいに](https://docs.djangoproject.com/ja/1.11/ref/templates/builtins/#include)引数を与えてインクルードすればいいようにしたい
組み込みタグを駆使してオブジェクト指向にしていこう、といった感じ
主に見やすさと拡張性を上げるため

**Comment by fazerog02** [comment]
a5bf734 で対応しました．

djangoのincludeの引数では変数を使えなかったので，購入確認用のダイアログと汎用ダイアログでファイルを分けました．

**Comment by fazerog02** [comment]
a5bf734 でとりあえずログアウトに確認ダイアログをつけました．

**Comment by sanoto** [comment]
ぬーん
CreateViewとかのクラスベースのビューはフォームとかリストとか自動生成してるからできないことはないきがするんだが・・・
なんかViewの実装に手を出さないといけないかな・・・
まあ取り敢えず切り出せたならいっかぁ
