### ISSUE TITLE
所持金がマイナスになる操作をするとinternal server error で落ちる

### ISSUE THREAD

**Issue by TYuto** [tnct-spc/kagipos#29]
/possys/api/add_transaction/<IDm>/<productid>/
で発生しました, 適当にエラーメッセージ等かえしてください

**Comment by sanoto** [comment]
あーそりゃ落ちるわ

**Comment by TYuto** [comment]
DBに反映する前に支払い能力()があるか確認して適当にお願いします

**Comment by sanoto** [comment]
エラーメッセージか・・・
まだレイズ系よくわかってないんだよね・・・
エラーメッセージってどんなのがよいの？

**Comment by TYuto** [comment]
いや, Pythonでの例外でなくて, 普通に日本語で "残高が足りません"とかでいいです, それをそのまま筐体の方で表示するので.

**Comment by TYuto** [comment]
(http requestの返り値として)

**Comment by sanoto** [comment]
普通にviewでやるのはできるんだけど、できればモデルのsaveメソッドあたりで弾きたいなーなんて思ったときにはレイズしなきゃだからそれで文字列返せんのかなーとかなんとか言って悩んでる
深いところからエラーメッセージ返そうっていう発想が違うのかねえ

**Comment by TYuto** [comment]
あーなるほど, 自分もPythonで例外作ったことないのでわからないですが, でも確かになんとなく viewで例外をキャッチして日本語のエラーにする気がする(?)

**Comment by sanoto** [comment]
viewでいちいちキャッチ処理書きたくない・・・

**Comment by TYuto** [comment]
一応raiseでエラーメッセージをつけれるっぽいですね
``` 
try:
    raise ValueError("error!")
except ValueError as e:
    print(e)
```
https://uxmilk.jp/39845
ただいずれにしろ例外処理はviewで書く必要がありそう(?)

**Comment by sanoto** [comment]
viewでエラーごとに処理分けなくていいならそれでいいか
じゃあ取り敢えずそれでやってみます

**Comment by TYuto** [comment]
お願いします

**Comment by sanoto** [comment]
修正しました
