### ISSUE TITLE
transactionの追加をSlackに流してほしい

### ISSUE THREAD

**Issue by TYuto** [tnct-spc/kagipos#31]
## 概要
possysは性善説によって成り立ってますが全員が善人とは限らないので全てのtransactionをSlackに流すようにしてほしい

## 注意
Slack incoming webhookをつかうと思いますが、URLをGitHubにあげてしまうと forceの力で歴史をねじ曲げないといけなくなるのでよしなに管理するようにお願いします

**Comment by sanoto** [comment]
まあ環境変数

**Comment by sanoto** [comment]
https://django-slack.readthedocs.io/
専用のライブラリ作ってるひとがいたwww

**Comment by sanoto** [comment]
あーこれトークン使うタイプのレガシーなやつなのか
