### ISSUE TITLE
取引履歴と商品リストの改良

### ISSUE THREAD

**Issue by sanoto** [tnct-spc/kagipos#38]
ListViewとかいうのがあるのでそれを使うようにする
どちらもquerysetをいいかんじにfilterとかで加工して使う
また、履歴の方は１履歴１行にして、内容は
`'チャージ'or商品名, 金額(符号付き), 日時`
でいいと思う

**Comment by fazerog02** [comment]
bb1cb26 で履歴は改良しました．
商品一覧についてはわりと大きな変更を加えようと思うので #37 で対応します．
